### PR TITLE
Create cspc27-ms2-2023-nov.nix

### PR DESCRIPTION
**Pull request by Zolo-Ryan**

### CODE REVIEW

**Comment by GetPsyched** [comment]
The marks total up to 17.5. Was there an OR question, @Zolo-Ryan?

**Comment by Zolo-Ryan** [comment]
The last question was of 5 marks. I missed updating it

**Review by GetPsyched — APPROVED** [review]
LGTM

**Comment by GetPsyched** [comment]
Thanks for the PR!

**Pull request merged**
