### PR TITLE
Adding Question Paper  CEPC31

### PR DESCRIPTION
**Pull request by AKCodeFanatic**
In this commit I have added a Nix file in the question-papers directory .
The file contains the contents of the question paper of the course CEPC31 of Mid Sem 2 which was taken on November 2 , 2023

### CODE REVIEW

**Review by GetPsyched — CHANGES_REQUESTED** [review]
LGTM. @AKCodeFanatic, is there any superscript/subscript missing after I've added the ones that I could find? If not, I think this is ready to merge.

**Comment by AKCodeFanatic** [comment]
> LGTM. @AKCodeFanatic, is there any superscript/subscript missing after I've added the ones that I could find? If not, I think this is ready to merge.

Sir I think the exponential(i.e square , cube) superscripts will work . So I think the PR is good to merge .

**Review by GetPsyched — APPROVED** [review]
Sounds good.

**Comment by AKCodeFanatic** [comment]
Thanks Sir !

**Comment by GetPsyched** [comment]
Thank _you_ for the PR! Feel free to add more papers if you have the time later :)

**Comment by AKCodeFanatic** [comment]
> Thank _you_ for the PR! Feel free to add more papers if you have the time later :)

Sure Sir !

**Pull request merged**
