### PR TITLE
Added CSPC31 and CSPC33

### PR DESCRIPTION
**Pull request by bhavaygoel**

### CODE REVIEW

**Comment by techsavvyash** [comment]
@GetPsyched Instead of going via this manual labour approach, try using this [EasyOCR](https://github.com/JaidedAI/EasyOCR)

**Comment by deepanshumidha5140** [comment]
Is someone working on this sir ?

**Comment by GetPsyched** [comment]
These just need to be updated by @bhavaygoel. There are some mistakes

**Comment by deepanshumidha5140** [comment]
Ok sir thenx

**Review by GetPsyched — APPROVED** [review]
Finally.

**Pull request merged**
